import fs from 'node:fs/promises';
import path from 'node:path';

export async function generateMigrationHub({ outDir, benchmarks }) {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'index.html'), renderHubIndex(benchmarks));
  await fs.writeFile(path.join(outDir, 'spring-boot-2-to-3.html'), renderMigrationPage(benchmarks));
}

export async function generateBenchmarkIndex({ outDir, reports }) {
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'index.html'), renderBenchmarkIndex(reports));
}

function renderHubIndex(benchmarks) {
  const rows = benchmarks.map((benchmark) => `<tr><td>${escapeHtml(benchmark.name)}</td><td><a href="${escapeHtml(benchmark.repository)}">${escapeHtml(benchmark.repository)}</a></td><td>${escapeHtml(benchmark.springBootVersion)}</td></tr>`).join('');
  return page('Migration Hub', `
    <section>
      <h1>Migration Hub</h1>
      <p>Guides, reports, examples, and benchmark evidence for mandatory enterprise modernization work.</p>
    </section>
    <section class="layout">
      <a class="tile" href="spring-boot-2-to-3.html"><strong>Spring Boot 2 to 3</strong><span>Readiness guide, risks, report shape, and benchmark catalog.</span></a>
      <a class="tile" href="../benchmarks/index.html"><strong>Benchmark Reports</strong><span>10 public benchmark reports generated by the CLI.</span></a>
    </section>
    <h2>Benchmark Set</h2>
    <table><thead><tr><th>Project</th><th>Repository</th><th>Spring Boot</th></tr></thead><tbody>${rows}</tbody></table>
  `);
}

function renderMigrationPage(benchmarks) {
  const links = benchmarks.map((benchmark) => `<li><a href="../benchmarks/${escapeHtml(benchmark.slug)}/index.html">${escapeHtml(benchmark.name)}</a></li>`).join('');
  return page('Spring Boot 2 to 3 Migration', `
    <section>
      <h1>Spring Boot 2 to 3 Migration</h1>
      <p>Initial readiness page for the first Enterprise Java modernization vertical.</p>
    </section>
    <h2>Guide</h2>
    <p>This guide focuses on readiness evidence: build metadata, Spring Boot version detection, Jakarta namespace risk, static source findings, and an HTML report that can be shared without a backend.</p>
    <h2>Readiness Signals</h2>
    <ul>
      <li>Explicit Maven or Gradle build metadata</li>
      <li>Spring Boot version discovery</li>
      <li>javax to jakarta migration risk</li>
      <li>Dependency injection and legacy API cleanup findings</li>
      <li>OpenRewrite dry-run readiness for the transformation flow</li>
    </ul>
    <h2>Benchmark Reports</h2>
    <ul>${links}</ul>
    <h2>FAQ</h2>
    <p><strong>Does readiness analysis apply migrations?</strong> No. It measures readiness and creates evidence. Apply, rollback, compile, and test validation are part of the transformation flow.</p>
  `);
}

function renderBenchmarkIndex(reports) {
  const rows = reports.map((report) => `<tr><td><a href="${escapeHtml(report.slug)}/index.html">${escapeHtml(report.name)}</a></td><td>${escapeHtml(formatReadiness(report.readiness))}</td><td>${escapeHtml(report.source || 'catalog')}</td><td><a href="${escapeHtml(report.repository)}">${escapeHtml(report.repository)}</a></td></tr>`).join('');
  return page('Benchmark Reports', `
    <section>
      <h1>Benchmark Reports</h1>
      <p>Benchmark reports generated from catalog metadata or real repository checkouts.</p>
    </section>
    <table><thead><tr><th>Project</th><th>Readiness</th><th>Source</th><th>Repository</th></tr></thead><tbody>${rows}</tbody></table>
  `);
}

function formatReadiness(readiness) {
  return readiness === null ? 'N/A' : `${readiness}%`;
}

function page(title, body) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { --ink:#17202a; --muted:#64748b; --line:#d8dee8; --bg:#f7f9fb; --panel:#fff; --accent:#1769aa; }
    * { box-sizing:border-box; }
    body { margin:0; font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; color:var(--ink); background:var(--bg); }
    main { max-width:1080px; margin:0 auto; padding:32px 24px; }
    h1 { margin:0 0 8px; font-size:34px; letter-spacing:0; }
    h2 { margin:28px 0 10px; font-size:21px; letter-spacing:0; }
    p { max-width:760px; color:var(--muted); }
    a { color:var(--accent); text-decoration:none; }
    a:hover { text-decoration:underline; }
    .layout { display:grid; grid-template-columns:repeat(2, minmax(0, 1fr)); gap:14px; margin:24px 0; }
    .tile { display:flex; flex-direction:column; gap:6px; min-height:118px; padding:18px; background:var(--panel); border:1px solid var(--line); border-radius:8px; color:var(--ink); }
    .tile span { color:var(--muted); }
    table { width:100%; border-collapse:collapse; background:var(--panel); border:1px solid var(--line); border-radius:8px; overflow:hidden; }
    th,td { text-align:left; padding:10px 12px; border-bottom:1px solid var(--line); vertical-align:top; }
    th { font-size:12px; color:var(--muted); text-transform:uppercase; }
    li { margin:6px 0; }
    @media (max-width: 720px) { .layout { grid-template-columns:1fr; } h1 { font-size:27px; } }
  </style>
</head>
<body><main>${body}</main></body>
</html>
`;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}
